### ISSUE TITLE
Can I use add_text after show_bitmap?

### ISSUE THREAD

**Issue by bsmntoid** [fizban99/microbit_ssd1306#12]
As the title says, can I use add_text to overlay text on top of a bitmap? Trying this stretches the bitmap and inverts it.

**Comment by fizban99** [comment]
This project is sort of abandoned, but I believe the issue is related to the fact that due to the low memory of micro:bit V1 all functions work in zoom mode and use a screen buffer except show_bitmap.  Also show_bitmap is the only one that inverts the sceen. The idea is that since the pixels on the screen are white, a bitmap is displayed inverted, but you will typically want to show the text as white on top of black.  Note also that the fact that show_bitmap does not use a buffer and loads directly the bitmap into the screen. This could probably be enhanced for micro:bit V2, since it has more memory available.

**Comment by bsmntoid** [comment]
ahhh, i see.
